In [15]:
import matplotlib.pyplot as plt
import numpy as np
import copy
import scipy.fft as fft
import astropy.constants as const
import astropy.units as u
from astropy.io import fits
from astropy.io import ascii
from astropy.convolution import Gaussian2DKernel
from astropy.cosmology import LambdaCDM
from photutils.segmentation import detect_threshold
from photutils.segmentation import detect_sources
from photutils.segmentation import deblend_sources
from photutils.segmentation import SourceCatalog
from scipy.interpolate import interp2d
from scipy.optimize import curve_fit
from math import pi
import csv

#----- Loading data
cat = ascii.read('bullet_435.cat')

#----- Morphological Properties
xcen = cat['X_IMAGE'].data
ycen = cat['Y_IMAGE'].data
phi = cat['THETA_IMAGE'].data

xmin = cat['XMIN_IMAGE'].data
xmax = cat['XMAX_IMAGE'].data  
ymin = cat['YMIN_IMAGE'].data
ymax = cat['YMAX_IMAGE'].data

a = cat['A_IMAGE'].data         # Profile RMS along major axis 라는데 확실히 맞는지는 모르겠다.
b = cat['B_IMAGE'].data 

#-----gamma, gamma1, gamma2
r = (a-b) / (a+b)
r1 = r * np.cos(2*phi)
r2 = r * np.sin(2*phi)

print(len(xcen), len(ycen), len(phi))

#-----Whisker Plot

r1_mean_list = np.array([])
r2_mean_list = np.array([])

for i in range(20):
    for j in range(20):
        ind = np.where( (255*i<ycen) & (ycen<255*(i+1)) & (350*j<xcen) & (xcen<350*(j+1)) )



4474 4474 4474
(array([ 3,  4,  5,  6,  7,  8,  9, 10]),)


In [18]:
print(np.zeros((2,3)).shape[1])

3


In [7]:
print(ind)

(array([], dtype=int64),)


In [4]:
a = np.zeros((1000,1000))

In [5]:
b = np.empty((1000,1000))

In [6]:
b = np.empty((1000000,1000000))

In [7]:
a = np.zeros((1000000,1000000))

In [34]:
print(max(xcen)) #7011.474
print(min(xcen)) #311.515

print(max(ycen)) #4638.641
print(min(ycen)) #311.515

print(min(xmin), max(xmax), min(ymin), max(ymax))
# min(xmin): 264, max(xmax): 7013, min(ymin):311, max(ymax):4643
image = np.zeros((5100,7013))
print(image)
print(image.shape)
rms = fits.open('bullet_f435w_RMS.fits')
rms = fits.open('bullet_f435w_drz_sci.fits')
print('절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선')
print(rms[0].header[3])
print('절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선')

print(rms[0].header)



# rms = fits.open('bullet_f435w_RMS.fits'), rms[0].shape : (5100, 7013)

7011.474
266.467
4638.641
311.515
264 7013 311 4643
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(5100, 7013)
절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선
7013
절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선절취선
SIMPLE  =                    T / Fits standard                                  BITPIX  =                  -32 / Bits per pixel                                 NAXIS   =                    2 / Number of axes                                 NAXIS1  =                 7013 / Axis length                                    NAXIS2  =                 5100 / Axis length                                    EXTEND  =                    T /Extensions may be present                       ORIGIN  = 'combDither, v1.47'  / FITS file originator                           DATE    = '2011-06-07T05:37:47Z'                                                FILENAME= 'bullet_f435w_drz_sci.fits' / name of file        

In [39]:
print(repr(rms[0].header))

SIMPLE  =                    T / Fits standard                                  
BITPIX  =                  -32 / Bits per pixel                                 
NAXIS   =                    2 / Number of axes                                 
NAXIS1  =                 7013 / Axis length                                    
NAXIS2  =                 5100 / Axis length                                    
EXTEND  =                    T /Extensions may be present                       
ORIGIN  = 'combDither, v1.47'  / FITS file originator                           
DATE    = '2011-06-07T05:37:47Z'                                                
FILENAME= 'bullet_f435w_drz_sci.fits' / name of file                            
FILETYPE= 'SCI     '                                                            
TELESCOP= 'HST     '           / telescope used to acquire data                 
INSTRUME= 'ACS     '           / identifier for instrument used to acquire data 
EXPTIME =               2420

In [58]:
print(len(list(rms[0].header.keys())))
print(rms.info())
cols = rms[1].columns


282
Filename: bullet_f435w_drz_sci.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     282   (7013, 5100)   float32   
None


IndexError: list index out of range

In [2]:
#-----Whisker Plot

r1_mean_list = np.array([])
r2_mean_list = np.array([])

for i in range(20):
    for j in range(20):
        ind = np.where( (255*i<ycen) & (ycen<255*(i+1)) & (350*i<xcen) * (xcen<350*(i+1)) )

In [5]:
print(ind)

(array([], dtype=int64),)
